// Generated by Rivet. Do not edit by hand.
import Foundation
import RivetRuntime

public enum RivetGeneratedError: Error { case typeMismatch(String); case unknownEvent(String) }
public enum RivetGeneratedConfig {
    public static let moduleName = "backend"
    public static let entryName = "start"
    public static let displayName = "MoveBit"
    public static let version = "1.5.0"
    public static let build: Int64 = 2
    public static let identifier = "site.jrtx.movebit"
    public static let releaseChannel = "stable"
}

public enum ReminderKind: String, Sendable {
    case sit = "sit"
    case water = "water"
    case micro = "micro"
}

public struct BreakEnded: Sendable {
    public let completed: Bool
    public init(completed: Bool) {
        self.completed = completed
    }
}

public struct BreakStarted: Sendable {
    public let duration_ms: Int64
    public let skip_after_ms: Int64
    public init(duration_ms: Int64, skip_after_ms: Int64) {
        self.duration_ms = duration_ms
        self.skip_after_ms = skip_after_ms
    }
}

public struct BreakState: Sendable {
    public let ends_at_ms: Int64
    public let skip_after_ms: Int64
    public let started_at_ms: Int64
    public init(ends_at_ms: Int64, skip_after_ms: Int64, started_at_ms: Int64) {
        self.ends_at_ms = ends_at_ms
        self.skip_after_ms = skip_after_ms
        self.started_at_ms = started_at_ms
    }
}

public struct DayStats: Sendable {
    public let date: String
    public let active_mins: Int64
    public let sit_breaks: Int64
    public let water_reminders: Int64
    public let micro_breaks: Int64
    public let longest_session_mins: Int64
    public init(date: String, active_mins: Int64, sit_breaks: Int64, water_reminders: Int64, micro_breaks: Int64, longest_session_mins: Int64) {
        self.date = date
        self.active_mins = active_mins
        self.sit_breaks = sit_breaks
        self.water_reminders = water_reminders
        self.micro_breaks = micro_breaks
        self.longest_session_mins = longest_session_mins
    }
}

public struct LoopInfo: Sendable {
    public let kind: ReminderKind
    public let due_in_active_mins: Int64?
    public let accumulated_mins: Int64
    public init(kind: ReminderKind, due_in_active_mins: Int64?, accumulated_mins: Int64) {
        self.kind = kind
        self.due_in_active_mins = due_in_active_mins
        self.accumulated_mins = accumulated_mins
    }
}

public struct PauseState: Sendable {
    public let paused: Bool
    public let until_ms: Int64?
    public init(paused: Bool, until_ms: Int64?) {
        self.paused = paused
        self.until_ms = until_ms
    }
}

public struct ReminderConfig: Sendable {
    public let sit_reminder_minutes: Int64
    public let water_reminder_minutes: Int64
    public let away_reset_minutes: Int64
    public let force_break_enabled: Bool
    public let break_duration_minutes: Int64
    public let skip_after_seconds: Int64
    public let snooze_minutes: Int64
    public let micro_break_enabled: Bool
    public let micro_break_interval_minutes: Int64
    public let micro_break_duration_seconds: Int64
    public let sound_enabled: Bool
    public let auto_check_updates: Bool
    public let welcome_shown: Bool
    public let language: String
    public init(sit_reminder_minutes: Int64, water_reminder_minutes: Int64, away_reset_minutes: Int64, force_break_enabled: Bool, break_duration_minutes: Int64, skip_after_seconds: Int64, snooze_minutes: Int64, micro_break_enabled: Bool, micro_break_interval_minutes: Int64, micro_break_duration_seconds: Int64, sound_enabled: Bool, auto_check_updates: Bool, welcome_shown: Bool, language: String) {
        self.sit_reminder_minutes = sit_reminder_minutes
        self.water_reminder_minutes = water_reminder_minutes
        self.away_reset_minutes = away_reset_minutes
        self.force_break_enabled = force_break_enabled
        self.break_duration_minutes = break_duration_minutes
        self.skip_after_seconds = skip_after_seconds
        self.snooze_minutes = snooze_minutes
        self.micro_break_enabled = micro_break_enabled
        self.micro_break_interval_minutes = micro_break_interval_minutes
        self.micro_break_duration_seconds = micro_break_duration_seconds
        self.sound_enabled = sound_enabled
        self.auto_check_updates = auto_check_updates
        self.welcome_shown = welcome_shown
        self.language = language
    }
}

public struct RemindersDue: Sendable {
    public let kinds: [ReminderKind]
    public let merged: Bool
    public init(kinds: [ReminderKind], merged: Bool) {
        self.kinds = kinds
        self.merged = merged
    }
}

private func encode_Void(_ v: Void) -> RivetValue { .null }
private func encode_Bool(_ v: Bool) -> RivetValue { .bool(v) }
private func encode_String(_ v: String) -> RivetValue { .string(v) }
private func encode_Int64(_ v: Int64) -> RivetValue { .int64(v) }
private func encode_DayStats(_ v: DayStats) -> RivetValue { .list([encode_String(v.date), encode_Int64(v.active_mins), encode_Int64(v.sit_breaks), encode_Int64(v.water_reminders), encode_Int64(v.micro_breaks), encode_Int64(v.longest_session_mins)]) }
private func encode__List_DayStats_(_ v: [DayStats]) -> RivetValue { .list(v.map(encode_DayStats)) }
private func encode_ReminderConfig(_ v: ReminderConfig) -> RivetValue { .list([encode_Int64(v.sit_reminder_minutes), encode_Int64(v.water_reminder_minutes), encode_Int64(v.away_reset_minutes), encode_Bool(v.force_break_enabled), encode_Int64(v.break_duration_minutes), encode_Int64(v.skip_after_seconds), encode_Int64(v.snooze_minutes), encode_Bool(v.micro_break_enabled), encode_Int64(v.micro_break_interval_minutes), encode_Int64(v.micro_break_duration_seconds), encode_Bool(v.sound_enabled), encode_Bool(v.auto_check_updates), encode_Bool(v.welcome_shown), encode_String(v.language)]) }
private func encode_ReminderKind(_ v: ReminderKind) -> RivetValue { .string(v.rawValue) }
private func encode_BreakEnded(_ v: BreakEnded) -> RivetValue { .list([encode_Bool(v.completed)]) }
private func encode_BreakStarted(_ v: BreakStarted) -> RivetValue { .list([encode_Int64(v.duration_ms), encode_Int64(v.skip_after_ms)]) }
private func encode__List_ReminderKind_(_ v: [ReminderKind]) -> RivetValue { .list(v.map(encode_ReminderKind)) }
private func encode_RemindersDue(_ v: RemindersDue) -> RivetValue { .list([encode__List_ReminderKind_(v.kinds), encode_Bool(v.merged)]) }
private func encode_BreakState(_ v: BreakState) -> RivetValue { .list([encode_Int64(v.ends_at_ms), encode_Int64(v.skip_after_ms), encode_Int64(v.started_at_ms)]) }
private func encode__Optional_BreakState_(_ v: BreakState?) -> RivetValue { v.map(encode_BreakState) ?? .null }
private func encode__Optional_Int64_(_ v: Int64?) -> RivetValue { v.map(encode_Int64) ?? .null }
private func encode_LoopInfo(_ v: LoopInfo) -> RivetValue { .list([encode_ReminderKind(v.kind), encode__Optional_Int64_(v.due_in_active_mins), encode_Int64(v.accumulated_mins)]) }
private func encode__List_LoopInfo_(_ v: [LoopInfo]) -> RivetValue { .list(v.map(encode_LoopInfo)) }
private func encode_PauseState(_ v: PauseState) -> RivetValue { .list([encode_Bool(v.paused), encode__Optional_Int64_(v.until_ms)]) }

private func decode_Void(_ v: RivetValue) throws -> Void { guard case .null = v else { throw RivetGeneratedError.typeMismatch("Void") } }
private func decode_Bool(_ v: RivetValue) throws -> Bool { guard case .bool(let x) = v else { throw RivetGeneratedError.typeMismatch("Bool") }; return x }
private func decode_String(_ v: RivetValue) throws -> String { guard case .string(let x) = v else { throw RivetGeneratedError.typeMismatch("String") }; return x }
private func decode_Int64(_ v: RivetValue) throws -> Int64 { guard case .int64(let x) = v else { throw RivetGeneratedError.typeMismatch("Int64") }; return x }
private func decode_DayStats(_ v: RivetValue) throws -> DayStats { guard case .list(let xs) = v, xs.count == 6 else { throw RivetGeneratedError.typeMismatch("DayStats") }; return DayStats(date: try decode_String(xs[0]), active_mins: try decode_Int64(xs[1]), sit_breaks: try decode_Int64(xs[2]), water_reminders: try decode_Int64(xs[3]), micro_breaks: try decode_Int64(xs[4]), longest_session_mins: try decode_Int64(xs[5])) }
private func decode__List_DayStats_(_ v: RivetValue) throws -> [DayStats] { guard case .list(let xs) = v else { throw RivetGeneratedError.typeMismatch("(List DayStats)") }; return try xs.map(decode_DayStats) }
private func decode_ReminderConfig(_ v: RivetValue) throws -> ReminderConfig { guard case .list(let xs) = v, xs.count == 14 else { throw RivetGeneratedError.typeMismatch("ReminderConfig") }; return ReminderConfig(sit_reminder_minutes: try decode_Int64(xs[0]), water_reminder_minutes: try decode_Int64(xs[1]), away_reset_minutes: try decode_Int64(xs[2]), force_break_enabled: try decode_Bool(xs[3]), break_duration_minutes: try decode_Int64(xs[4]), skip_after_seconds: try decode_Int64(xs[5]), snooze_minutes: try decode_Int64(xs[6]), micro_break_enabled: try decode_Bool(xs[7]), micro_break_interval_minutes: try decode_Int64(xs[8]), micro_break_duration_seconds: try decode_Int64(xs[9]), sound_enabled: try decode_Bool(xs[10]), auto_check_updates: try decode_Bool(xs[11]), welcome_shown: try decode_Bool(xs[12]), language: try decode_String(xs[13])) }
private func decode_ReminderKind(_ v: RivetValue) throws -> ReminderKind { guard case .string(let x) = v, let result = ReminderKind(rawValue: x) else { throw RivetGeneratedError.typeMismatch("ReminderKind") }; return result }
private func decode_BreakEnded(_ v: RivetValue) throws -> BreakEnded { guard case .list(let xs) = v, xs.count == 1 else { throw RivetGeneratedError.typeMismatch("BreakEnded") }; return BreakEnded(completed: try decode_Bool(xs[0])) }
private func decode_BreakStarted(_ v: RivetValue) throws -> BreakStarted { guard case .list(let xs) = v, xs.count == 2 else { throw RivetGeneratedError.typeMismatch("BreakStarted") }; return BreakStarted(duration_ms: try decode_Int64(xs[0]), skip_after_ms: try decode_Int64(xs[1])) }
private func decode__List_ReminderKind_(_ v: RivetValue) throws -> [ReminderKind] { guard case .list(let xs) = v else { throw RivetGeneratedError.typeMismatch("(List ReminderKind)") }; return try xs.map(decode_ReminderKind) }
private func decode_RemindersDue(_ v: RivetValue) throws -> RemindersDue { guard case .list(let xs) = v, xs.count == 2 else { throw RivetGeneratedError.typeMismatch("RemindersDue") }; return RemindersDue(kinds: try decode__List_ReminderKind_(xs[0]), merged: try decode_Bool(xs[1])) }
private func decode_BreakState(_ v: RivetValue) throws -> BreakState { guard case .list(let xs) = v, xs.count == 3 else { throw RivetGeneratedError.typeMismatch("BreakState") }; return BreakState(ends_at_ms: try decode_Int64(xs[0]), skip_after_ms: try decode_Int64(xs[1]), started_at_ms: try decode_Int64(xs[2])) }
private func decode__Optional_BreakState_(_ v: RivetValue) throws -> BreakState? { if case .null = v { return nil }; return try decode_BreakState(v) }
private func decode__Optional_Int64_(_ v: RivetValue) throws -> Int64? { if case .null = v { return nil }; return try decode_Int64(v) }
private func decode_LoopInfo(_ v: RivetValue) throws -> LoopInfo { guard case .list(let xs) = v, xs.count == 3 else { throw RivetGeneratedError.typeMismatch("LoopInfo") }; return LoopInfo(kind: try decode_ReminderKind(xs[0]), due_in_active_mins: try decode__Optional_Int64_(xs[1]), accumulated_mins: try decode_Int64(xs[2])) }
private func decode__List_LoopInfo_(_ v: RivetValue) throws -> [LoopInfo] { guard case .list(let xs) = v else { throw RivetGeneratedError.typeMismatch("(List LoopInfo)") }; return try xs.map(decode_LoopInfo) }
private func decode_PauseState(_ v: RivetValue) throws -> PauseState { guard case .list(let xs) = v, xs.count == 2 else { throw RivetGeneratedError.typeMismatch("PauseState") }; return PauseState(paused: try decode_Bool(xs[0]), until_ms: try decode__Optional_Int64_(xs[1])) }

public enum RivetEvent: Sendable {
    case break_ended(BreakEnded)
    case break_started(BreakStarted)
    case config_changed(ReminderConfig)
    case day_completed(DayStats)
    case reminders_due(RemindersDue)
    case tick_stats(DayStats)

    public static func decode(name: String, value: RivetValue) throws -> RivetEvent {
        switch name {
        case "break-ended": return .break_ended(try decode_BreakEnded(value))
        case "break-started": return .break_started(try decode_BreakStarted(value))
        case "config-changed": return .config_changed(try decode_ReminderConfig(value))
        case "day-completed": return .day_completed(try decode_DayStats(value))
        case "reminders-due": return .reminders_due(try decode_RemindersDue(value))
        case "tick-stats": return .tick_stats(try decode_DayStats(value))
        default: throw RivetGeneratedError.unknownEvent(name)
        }
    }
}

public struct RivetAPI: Sendable {
    public let client: RivetClient
    public init(client: RivetClient) { self.client = client }

    public func complete_break() async throws -> Void {
        let result = try await client.call("complete-break", arguments: [])
        return try decode_Void(result)
    }
    public func flush_now() async throws -> Void {
        let result = try await client.call("flush-now", arguments: [])
        return try decode_Void(result)
    }
    public func get_autostart() async throws -> Bool {
        let result = try await client.call("get-autostart", arguments: [])
        return try decode_Bool(result)
    }
    public func get_diagnostics() async throws -> String {
        let result = try await client.call("get-diagnostics", arguments: [])
        return try decode_String(result)
    }
    public func get_history(days: Int64) async throws -> [DayStats] {
        let result = try await client.call("get-history", arguments: [encode_Int64(days)])
        return try decode__List_DayStats_(result)
    }
    public func initialize() async throws -> Void {
        let result = try await client.call("initialize", arguments: [])
        return try decode_Void(result)
    }
    public func pause_1h() async throws -> Void {
        let result = try await client.call("pause-1h", arguments: [])
        return try decode_Void(result)
    }
    public func resume() async throws -> Void {
        let result = try await client.call("resume", arguments: [])
        return try decode_Void(result)
    }
    public func set_autostart(enabled: Bool) async throws -> Void {
        let result = try await client.call("set-autostart", arguments: [encode_Bool(enabled)])
        return try decode_Void(result)
    }
    public func set_config(value: ReminderConfig) async throws -> Void {
        let result = try await client.call("set-config", arguments: [encode_ReminderConfig(value)])
        return try decode_Void(result)
    }
    public func skip_break() async throws -> Void {
        let result = try await client.call("skip-break", arguments: [])
        return try decode_Void(result)
    }
    public func snooze(kind: ReminderKind) async throws -> Void {
        let result = try await client.call("snooze", arguments: [encode_ReminderKind(kind)])
        return try decode_Void(result)
    }

    // Shared state
    public func getActive_config() async throws -> ReminderConfig {
        let result = try await client.getState("active-config")
        return try decode_ReminderConfig(result)
    }
    @discardableResult
    public func setActive_config(_ value: ReminderConfig) async throws -> ReminderConfig {
        let result = try await client.setState("active-config", value: encode_ReminderConfig(value))
        return try decode_ReminderConfig(result)
    }
    public func getBreak_active() async throws -> BreakState? {
        let result = try await client.getState("break-active")
        return try decode__Optional_BreakState_(result)
    }
    @discardableResult
    public func setBreak_active(_ value: BreakState?) async throws -> BreakState? {
        let result = try await client.setState("break-active", value: encode__Optional_BreakState_(value))
        return try decode__Optional_BreakState_(result)
    }
    public func getLoops() async throws -> [LoopInfo] {
        let result = try await client.getState("loops")
        return try decode__List_LoopInfo_(result)
    }
    @discardableResult
    public func setLoops(_ value: [LoopInfo]) async throws -> [LoopInfo] {
        let result = try await client.setState("loops", value: encode__List_LoopInfo_(value))
        return try decode__List_LoopInfo_(result)
    }
    public func getPaused() async throws -> PauseState {
        let result = try await client.getState("paused")
        return try decode_PauseState(result)
    }
    @discardableResult
    public func setPaused(_ value: PauseState) async throws -> PauseState {
        let result = try await client.setState("paused", value: encode_PauseState(value))
        return try decode_PauseState(result)
    }
    public func getToday() async throws -> DayStats {
        let result = try await client.getState("today")
        return try decode_DayStats(result)
    }
    @discardableResult
    public func setToday(_ value: DayStats) async throws -> DayStats {
        let result = try await client.setState("today", value: encode_DayStats(value))
        return try decode_DayStats(result)
    }
}
