// Generated by Rivet. Do not edit by hand.
#pragma once

#include <cstdint>
#include <exception>
#include <functional>
#include <future>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <variant>
#include <vector>

#include "backend.hpp"

namespace rivet_app {
inline constexpr char kModuleName[] = "backend";
inline constexpr char kEntryName[] = "start";
inline constexpr char kDisplayName[] = "MoveBit";
inline constexpr char kVersion[] = "1.5.0";
inline constexpr std::int64_t kBuild = 2;
inline constexpr char kIdentifier[] = "site.jrtx.movebit";
inline constexpr char kReleaseChannel[] = "stable";

enum class ReminderKind { sit, water, micro };

struct BreakEnded {
  bool completed;
};

struct BreakStarted {
  std::int64_t duration_ms;
  std::int64_t skip_after_ms;
};

struct BreakState {
  std::int64_t ends_at_ms;
  std::int64_t skip_after_ms;
  std::int64_t started_at_ms;
};

struct DayStats {
  std::string date;
  std::int64_t active_mins;
  std::int64_t sit_breaks;
  std::int64_t water_reminders;
  std::int64_t micro_breaks;
  std::int64_t longest_session_mins;
};

struct LoopInfo {
  ReminderKind kind;
  std::optional<std::int64_t> due_in_active_mins;
  std::int64_t accumulated_mins;
};

struct PauseState {
  bool paused;
  std::optional<std::int64_t> until_ms;
};

struct ReminderConfig {
  std::int64_t sit_reminder_minutes;
  std::int64_t water_reminder_minutes;
  std::int64_t away_reset_minutes;
  bool force_break_enabled;
  std::int64_t break_duration_minutes;
  std::int64_t skip_after_seconds;
  std::int64_t snooze_minutes;
  bool micro_break_enabled;
  std::int64_t micro_break_interval_minutes;
  std::int64_t micro_break_duration_seconds;
  bool sound_enabled;
  bool auto_check_updates;
  bool welcome_shown;
  std::string language;
};

struct RemindersDue {
  std::vector<ReminderKind> kinds;
  bool merged;
};

template <typename T>
struct Result {
  std::optional<T> value;
  std::exception_ptr error;
  bool succeeded() const noexcept { return value.has_value() && !error; }
  T const& get() const { if (error) std::rethrow_exception(error); if (!value) throw std::runtime_error("Rivet async result has no value"); return *value; }
};

template <>
struct Result<void> {
  std::exception_ptr error;
  bool succeeded() const noexcept { return !error; }
  void get() const { if (error) std::rethrow_exception(error); }
};

namespace detail {
inline rivet::Value encode_Void() { return rivet::Value{}; }
inline rivet::Value encode_Bool(bool v) { return rivet::Value(v); }
inline rivet::Value encode_String(std::string const& v) { return rivet::Value(v); }
inline rivet::Value encode_Int64(std::int64_t v) { return rivet::Value(v); }
inline rivet::Value encode_DayStats(DayStats const& v) { rivet::Value::List r; r.reserve(6); r.push_back(encode_String(v.date)); r.push_back(encode_Int64(v.active_mins)); r.push_back(encode_Int64(v.sit_breaks)); r.push_back(encode_Int64(v.water_reminders)); r.push_back(encode_Int64(v.micro_breaks)); r.push_back(encode_Int64(v.longest_session_mins)); return rivet::Value(std::move(r)); }
inline rivet::Value encode__List_DayStats_(std::vector<DayStats> const& xs) { rivet::Value::List r; r.reserve(xs.size()); for (auto const& x : xs) r.push_back(encode_DayStats(x)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_ReminderConfig(ReminderConfig const& v) { rivet::Value::List r; r.reserve(14); r.push_back(encode_Int64(v.sit_reminder_minutes)); r.push_back(encode_Int64(v.water_reminder_minutes)); r.push_back(encode_Int64(v.away_reset_minutes)); r.push_back(encode_Bool(v.force_break_enabled)); r.push_back(encode_Int64(v.break_duration_minutes)); r.push_back(encode_Int64(v.skip_after_seconds)); r.push_back(encode_Int64(v.snooze_minutes)); r.push_back(encode_Bool(v.micro_break_enabled)); r.push_back(encode_Int64(v.micro_break_interval_minutes)); r.push_back(encode_Int64(v.micro_break_duration_seconds)); r.push_back(encode_Bool(v.sound_enabled)); r.push_back(encode_Bool(v.auto_check_updates)); r.push_back(encode_Bool(v.welcome_shown)); r.push_back(encode_String(v.language)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_ReminderKind(ReminderKind v) { switch (v) { case ReminderKind::sit: return rivet::Value(std::string("sit")); case ReminderKind::water: return rivet::Value(std::string("water")); case ReminderKind::micro: return rivet::Value(std::string("micro")); } throw std::runtime_error("invalid Rivet enum value"); }
inline rivet::Value encode_BreakEnded(BreakEnded const& v) { rivet::Value::List r; r.reserve(1); r.push_back(encode_Bool(v.completed)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_BreakStarted(BreakStarted const& v) { rivet::Value::List r; r.reserve(2); r.push_back(encode_Int64(v.duration_ms)); r.push_back(encode_Int64(v.skip_after_ms)); return rivet::Value(std::move(r)); }
inline rivet::Value encode__List_ReminderKind_(std::vector<ReminderKind> const& xs) { rivet::Value::List r; r.reserve(xs.size()); for (auto const& x : xs) r.push_back(encode_ReminderKind(x)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_RemindersDue(RemindersDue const& v) { rivet::Value::List r; r.reserve(2); r.push_back(encode__List_ReminderKind_(v.kinds)); r.push_back(encode_Bool(v.merged)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_BreakState(BreakState const& v) { rivet::Value::List r; r.reserve(3); r.push_back(encode_Int64(v.ends_at_ms)); r.push_back(encode_Int64(v.skip_after_ms)); r.push_back(encode_Int64(v.started_at_ms)); return rivet::Value(std::move(r)); }
inline rivet::Value encode__Optional_BreakState_(std::optional<BreakState> const& v) { return v ? encode_BreakState(*v) : rivet::Value{}; }
inline rivet::Value encode__Optional_Int64_(std::optional<std::int64_t> const& v) { return v ? encode_Int64(*v) : rivet::Value{}; }
inline rivet::Value encode_LoopInfo(LoopInfo const& v) { rivet::Value::List r; r.reserve(3); r.push_back(encode_ReminderKind(v.kind)); r.push_back(encode__Optional_Int64_(v.due_in_active_mins)); r.push_back(encode_Int64(v.accumulated_mins)); return rivet::Value(std::move(r)); }
inline rivet::Value encode__List_LoopInfo_(std::vector<LoopInfo> const& xs) { rivet::Value::List r; r.reserve(xs.size()); for (auto const& x : xs) r.push_back(encode_LoopInfo(x)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_PauseState(PauseState const& v) { rivet::Value::List r; r.reserve(2); r.push_back(encode_Bool(v.paused)); r.push_back(encode__Optional_Int64_(v.until_ms)); return rivet::Value(std::move(r)); }

inline void decode_Void(rivet::Value const& v) { if (!std::holds_alternative<std::monostate>(v.data)) throw std::runtime_error("Rivet result type mismatch: Void"); }
inline bool decode_Bool(rivet::Value const& v) { if (auto p = std::get_if<bool>(&v.data)) return *p; throw std::runtime_error("Rivet result type mismatch: Bool"); }
inline std::string decode_String(rivet::Value const& v) { if (auto p = std::get_if<std::string>(&v.data)) return *p; throw std::runtime_error("Rivet result type mismatch: String"); }
inline std::int64_t decode_Int64(rivet::Value const& v) { if (auto p = std::get_if<std::int64_t>(&v.data)) return *p; throw std::runtime_error("Rivet result type mismatch: Int64"); }
inline DayStats decode_DayStats(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 6) throw std::runtime_error("Rivet result type mismatch: DayStats"); return DayStats{decode_String((*p)[0]), decode_Int64((*p)[1]), decode_Int64((*p)[2]), decode_Int64((*p)[3]), decode_Int64((*p)[4]), decode_Int64((*p)[5])}; }
inline std::vector<DayStats> decode__List_DayStats_(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p) throw std::runtime_error("Rivet result type mismatch: (List DayStats)"); std::vector<DayStats> r; r.reserve(p->size()); for (auto const& x : *p) r.push_back(decode_DayStats(x)); return r; }
inline ReminderConfig decode_ReminderConfig(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 14) throw std::runtime_error("Rivet result type mismatch: ReminderConfig"); return ReminderConfig{decode_Int64((*p)[0]), decode_Int64((*p)[1]), decode_Int64((*p)[2]), decode_Bool((*p)[3]), decode_Int64((*p)[4]), decode_Int64((*p)[5]), decode_Int64((*p)[6]), decode_Bool((*p)[7]), decode_Int64((*p)[8]), decode_Int64((*p)[9]), decode_Bool((*p)[10]), decode_Bool((*p)[11]), decode_Bool((*p)[12]), decode_String((*p)[13])}; }
inline ReminderKind decode_ReminderKind(rivet::Value const& v) { auto p = std::get_if<std::string>(&v.data); if (p) { if (*p == "sit") return ReminderKind::sit; if (*p == "water") return ReminderKind::water; if (*p == "micro") return ReminderKind::micro; } throw std::runtime_error("Rivet result type mismatch: ReminderKind"); }
inline BreakEnded decode_BreakEnded(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 1) throw std::runtime_error("Rivet result type mismatch: BreakEnded"); return BreakEnded{decode_Bool((*p)[0])}; }
inline BreakStarted decode_BreakStarted(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 2) throw std::runtime_error("Rivet result type mismatch: BreakStarted"); return BreakStarted{decode_Int64((*p)[0]), decode_Int64((*p)[1])}; }
inline std::vector<ReminderKind> decode__List_ReminderKind_(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p) throw std::runtime_error("Rivet result type mismatch: (List ReminderKind)"); std::vector<ReminderKind> r; r.reserve(p->size()); for (auto const& x : *p) r.push_back(decode_ReminderKind(x)); return r; }
inline RemindersDue decode_RemindersDue(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 2) throw std::runtime_error("Rivet result type mismatch: RemindersDue"); return RemindersDue{decode__List_ReminderKind_((*p)[0]), decode_Bool((*p)[1])}; }
inline BreakState decode_BreakState(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 3) throw std::runtime_error("Rivet result type mismatch: BreakState"); return BreakState{decode_Int64((*p)[0]), decode_Int64((*p)[1]), decode_Int64((*p)[2])}; }
inline std::optional<BreakState> decode__Optional_BreakState_(rivet::Value const& v) { if (std::holds_alternative<std::monostate>(v.data)) return std::nullopt; return decode_BreakState(v); }
inline std::optional<std::int64_t> decode__Optional_Int64_(rivet::Value const& v) { if (std::holds_alternative<std::monostate>(v.data)) return std::nullopt; return decode_Int64(v); }
inline LoopInfo decode_LoopInfo(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 3) throw std::runtime_error("Rivet result type mismatch: LoopInfo"); return LoopInfo{decode_ReminderKind((*p)[0]), decode__Optional_Int64_((*p)[1]), decode_Int64((*p)[2])}; }
inline std::vector<LoopInfo> decode__List_LoopInfo_(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p) throw std::runtime_error("Rivet result type mismatch: (List LoopInfo)"); std::vector<LoopInfo> r; r.reserve(p->size()); for (auto const& x : *p) r.push_back(decode_LoopInfo(x)); return r; }
inline PauseState decode_PauseState(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 2) throw std::runtime_error("Rivet result type mismatch: PauseState"); return PauseState{decode_Bool((*p)[0]), decode__Optional_Int64_((*p)[1])}; }
}  // namespace detail

struct Break_endedEvent { BreakEnded value; };
struct Break_startedEvent { BreakStarted value; };
struct Config_changedEvent { ReminderConfig value; };
struct Day_completedEvent { DayStats value; };
struct Reminders_dueEvent { RemindersDue value; };
struct Tick_statsEvent { DayStats value; };
using Event = std::variant<Break_endedEvent, Break_startedEvent, Config_changedEvent, Day_completedEvent, Reminders_dueEvent, Tick_statsEvent>;
inline Event decode_event(std::string const& name, rivet::Value const& value) {
  if (name == "break-ended") return Event{Break_endedEvent{detail::decode_BreakEnded(value)}};
  if (name == "break-started") return Event{Break_startedEvent{detail::decode_BreakStarted(value)}};
  if (name == "config-changed") return Event{Config_changedEvent{detail::decode_ReminderConfig(value)}};
  if (name == "day-completed") return Event{Day_completedEvent{detail::decode_DayStats(value)}};
  if (name == "reminders-due") return Event{Reminders_dueEvent{detail::decode_RemindersDue(value)}};
  if (name == "tick-stats") return Event{Tick_statsEvent{detail::decode_DayStats(value)}};
  throw std::runtime_error("unknown Rivet event: " + name);
}

class API {
 public:
  explicit API(rivet::linux_runtime::Backend& backend) : backend_(backend) {}

  std::future<void> complete_break() { auto raw = backend_.call("complete-break", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> void { detail::decode_Void(raw.get()); }); }
  [[nodiscard]] std::uint64_t complete_break_async(std::function<void(Result<void>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("complete-break", rivet::Value::List{}, [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<void> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); detail::decode_Void(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<void> flush_now() { auto raw = backend_.call("flush-now", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> void { detail::decode_Void(raw.get()); }); }
  [[nodiscard]] std::uint64_t flush_now_async(std::function<void(Result<void>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("flush-now", rivet::Value::List{}, [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<void> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); detail::decode_Void(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<bool> get_autostart() { auto raw = backend_.call("get-autostart", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> bool { return detail::decode_Bool(raw.get()); }); }
  [[nodiscard]] std::uint64_t get_autostart_async(std::function<void(Result<bool>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("get-autostart", rivet::Value::List{}, [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<bool> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_Bool(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<std::string> get_diagnostics() { auto raw = backend_.call("get-diagnostics", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::string { return detail::decode_String(raw.get()); }); }
  [[nodiscard]] std::uint64_t get_diagnostics_async(std::function<void(Result<std::string>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("get-diagnostics", rivet::Value::List{}, [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<std::string> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_String(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<std::vector<DayStats>> get_history(std::int64_t days) { auto raw = backend_.call("get-history", rivet::Value::List{detail::encode_Int64(days)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::vector<DayStats> { return detail::decode__List_DayStats_(raw.get()); }); }
  [[nodiscard]] std::uint64_t get_history_async(std::int64_t days, std::function<void(Result<std::vector<DayStats>>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("get-history", rivet::Value::List{detail::encode_Int64(days)}, [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<std::vector<DayStats>> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode__List_DayStats_(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<void> initialize() { auto raw = backend_.call("initialize", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> void { detail::decode_Void(raw.get()); }); }
  [[nodiscard]] std::uint64_t initialize_async(std::function<void(Result<void>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("initialize", rivet::Value::List{}, [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<void> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); detail::decode_Void(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<void> pause_1h() { auto raw = backend_.call("pause-1h", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> void { detail::decode_Void(raw.get()); }); }
  [[nodiscard]] std::uint64_t pause_1h_async(std::function<void(Result<void>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("pause-1h", rivet::Value::List{}, [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<void> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); detail::decode_Void(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<void> resume() { auto raw = backend_.call("resume", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> void { detail::decode_Void(raw.get()); }); }
  [[nodiscard]] std::uint64_t resume_async(std::function<void(Result<void>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("resume", rivet::Value::List{}, [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<void> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); detail::decode_Void(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<void> set_autostart(bool enabled) { auto raw = backend_.call("set-autostart", rivet::Value::List{detail::encode_Bool(enabled)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> void { detail::decode_Void(raw.get()); }); }
  [[nodiscard]] std::uint64_t set_autostart_async(bool enabled, std::function<void(Result<void>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("set-autostart", rivet::Value::List{detail::encode_Bool(enabled)}, [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<void> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); detail::decode_Void(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<void> set_config(ReminderConfig value) { auto raw = backend_.call("set-config", rivet::Value::List{detail::encode_ReminderConfig(value)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> void { detail::decode_Void(raw.get()); }); }
  [[nodiscard]] std::uint64_t set_config_async(ReminderConfig value, std::function<void(Result<void>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("set-config", rivet::Value::List{detail::encode_ReminderConfig(value)}, [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<void> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); detail::decode_Void(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<void> skip_break() { auto raw = backend_.call("skip-break", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> void { detail::decode_Void(raw.get()); }); }
  [[nodiscard]] std::uint64_t skip_break_async(std::function<void(Result<void>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("skip-break", rivet::Value::List{}, [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<void> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); detail::decode_Void(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<void> snooze(ReminderKind kind) { auto raw = backend_.call("snooze", rivet::Value::List{detail::encode_ReminderKind(kind)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> void { detail::decode_Void(raw.get()); }); }
  [[nodiscard]] std::uint64_t snooze_async(ReminderKind kind, std::function<void(Result<void>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("snooze", rivet::Value::List{detail::encode_ReminderKind(kind)}, [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<void> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); detail::decode_Void(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }

  // Shared state
  std::future<ReminderConfig> get_active_config() { auto raw = backend_.get_state("active-config"); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> ReminderConfig { return detail::decode_ReminderConfig(raw.get()); }); }
  [[nodiscard]] std::uint64_t get_active_config_async(std::function<void(Result<ReminderConfig>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.get_state_async("active-config", [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<ReminderConfig> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_ReminderConfig(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<ReminderConfig> set_active_config(ReminderConfig value) { auto raw = backend_.set_state("active-config", detail::encode_ReminderConfig(value)); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> ReminderConfig { return detail::decode_ReminderConfig(raw.get()); }); }
  [[nodiscard]] std::uint64_t set_active_config_async(ReminderConfig value, std::function<void(Result<ReminderConfig>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.set_state_async("active-config", detail::encode_ReminderConfig(value), [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<ReminderConfig> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_ReminderConfig(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<std::optional<BreakState>> get_break_active() { auto raw = backend_.get_state("break-active"); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::optional<BreakState> { return detail::decode__Optional_BreakState_(raw.get()); }); }
  [[nodiscard]] std::uint64_t get_break_active_async(std::function<void(Result<std::optional<BreakState>>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.get_state_async("break-active", [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<std::optional<BreakState>> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode__Optional_BreakState_(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<std::optional<BreakState>> set_break_active(std::optional<BreakState> value) { auto raw = backend_.set_state("break-active", detail::encode__Optional_BreakState_(value)); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::optional<BreakState> { return detail::decode__Optional_BreakState_(raw.get()); }); }
  [[nodiscard]] std::uint64_t set_break_active_async(std::optional<BreakState> value, std::function<void(Result<std::optional<BreakState>>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.set_state_async("break-active", detail::encode__Optional_BreakState_(value), [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<std::optional<BreakState>> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode__Optional_BreakState_(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<std::vector<LoopInfo>> get_loops() { auto raw = backend_.get_state("loops"); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::vector<LoopInfo> { return detail::decode__List_LoopInfo_(raw.get()); }); }
  [[nodiscard]] std::uint64_t get_loops_async(std::function<void(Result<std::vector<LoopInfo>>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.get_state_async("loops", [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<std::vector<LoopInfo>> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode__List_LoopInfo_(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<std::vector<LoopInfo>> set_loops(std::vector<LoopInfo> value) { auto raw = backend_.set_state("loops", detail::encode__List_LoopInfo_(value)); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::vector<LoopInfo> { return detail::decode__List_LoopInfo_(raw.get()); }); }
  [[nodiscard]] std::uint64_t set_loops_async(std::vector<LoopInfo> value, std::function<void(Result<std::vector<LoopInfo>>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.set_state_async("loops", detail::encode__List_LoopInfo_(value), [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<std::vector<LoopInfo>> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode__List_LoopInfo_(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<PauseState> get_paused() { auto raw = backend_.get_state("paused"); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> PauseState { return detail::decode_PauseState(raw.get()); }); }
  [[nodiscard]] std::uint64_t get_paused_async(std::function<void(Result<PauseState>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.get_state_async("paused", [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<PauseState> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_PauseState(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<PauseState> set_paused(PauseState value) { auto raw = backend_.set_state("paused", detail::encode_PauseState(value)); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> PauseState { return detail::decode_PauseState(raw.get()); }); }
  [[nodiscard]] std::uint64_t set_paused_async(PauseState value, std::function<void(Result<PauseState>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.set_state_async("paused", detail::encode_PauseState(value), [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<PauseState> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_PauseState(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<DayStats> get_today() { auto raw = backend_.get_state("today"); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> DayStats { return detail::decode_DayStats(raw.get()); }); }
  [[nodiscard]] std::uint64_t get_today_async(std::function<void(Result<DayStats>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.get_state_async("today", [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<DayStats> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_DayStats(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<DayStats> set_today(DayStats value) { auto raw = backend_.set_state("today", detail::encode_DayStats(value)); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> DayStats { return detail::decode_DayStats(raw.get()); }); }
  [[nodiscard]] std::uint64_t set_today_async(DayStats value, std::function<void(Result<DayStats>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.set_state_async("today", detail::encode_DayStats(value), [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<DayStats> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_DayStats(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }

 private:
  rivet::linux_runtime::Backend& backend_;
};

}  // namespace rivet_app
